services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    
    # Start the backend only when postgres container has started and 
    # the postgres daemon has started accepting connections
    depends_on:
      postgres:
        condition: service_healthy
    
    expose:
      - "8000"
    
  postgres:
    image: postgres:17
    
    # This is just for testing
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=codereview_db
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    # When changing user params above, remember to change here too    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d codereview_db"]
      interval: 1s
      timeout: 5s
      retries: 5 

volumes:
  postgres_data:


